name: Sync fork from upstream

on:
  schedule:
    # 09:00 UTC daily (adjust as you like)
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  contents: write  # GITHUB_TOKEN may need write for pushing updated refs

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fast-forward main from upstream
        id: sync_upstream
        run: |
          set -euo pipefail
          API="https://api.github.com/repos/${{ github.repository }}/merge-upstream"
          BODY='{"branch":"main"}'
          # Call the API and capture HTTP status
          HTTP_STATUS=$(curl -sS -o resp.json -w "%{http_code}" -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "$API" -d "$BODY")
          echo "HTTP_STATUS=$HTTP_STATUS"
          cat resp.json || true
          # 200 = fast-forwarded; 409 = conflicts; 422 = other issues
          test "$HTTP_STATUS" -eq 200 || exit 1
